services:
  client:
    build:
      context: ./client
      dockerfile: dockerfile
    container_name: powow-client
    environment:
      - VITE_DOCKER_URL=http://localhost:3001
    ports:
      - '3000:3000'
    networks:
      - powow
  server:
    build:
      context: ./server
      dockerfile: dockerfile
    container_name: powow-server
    env_file:
      - ./server/.env
    ports:
      - '3001:3001'
    networks:
      - powow
networks:
  powow:
    driver: bridge

